package com.kaushik.railway.nav

object Routes {
    const val Splash = "splash"
    const val Login = "login"
    const val Unlock = "unlock"
    const val Register = "register"
    const val Activate = "activate"
    const val Mpin = "mpin"
    const val Aadhaar = "aadhaar"
    const val Verify = "verify"
    const val Home = "home"
    const val Trains = "trains"
    const val Availability = "availability"
    const val Vacancy = "vacancy"
    const val Passengers = "passengers"
    const val Review = "review"
    const val Payment = "payment"
    const val Ticket = "ticket"
    const val Pnr = "pnr"
    const val Running = "running"
    const val Bookings = "bookings"
    const val Profile = "profile"
    const val More = "more"
}
